{{- $fullName := include "velocity-lead-service.fullname" . -}}
{{- $hostname := include "velocity-lead-service.dnsname" . -}}
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  {{ $fullName }}
spec:
  ambassador_id: {{ .Values.ambassador.id }}
  prefix: /
  host: {{ $hostname }}
  service: {{ $fullName }}
  timeout_ms: 0