apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "velocity-lead-service.fullname" . }}-environment
  labels:
    {{- include "velocity-lead-service.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ tpl $val $ | quote }}
{{- end }}
