deploymentEnvironment: production

environment:
  ENV: preproduction
  SITE_ENV_DOMAIN_NAME: velocity-lead-service.api.canstar.com.au
  # PORT
  PORT: '3000'

ambassador:
  id: internal

podSecurityContext:
  fsGroup: 2000

serviceaccount:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# serviceAccount:
#   annotations: 
#     eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/<role-name>